GestorReunionesProyectoAnalisis/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using GestorReunionesProyectoAnalisis.Models;
using GestorReunionesProyectoAplicada.Business;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace GestorReunionesProyectoAplicada.Controllers
{
    public class DashboardController : Controller
    {
        public IConfiguration Configuration { get; }

        public DashboardController(IConfiguration configuration)
        {
            Configuration = configuration;
        } // constructor

        //Muestra la vista de Dashboard
        public IActionResult Index()
        {
            ViewBag.INVALIDO = null;
            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
            return View("DashboardView");
        }


        //Se encarga de cargar todos los datos en la vista de Dashboard
        public IActionResult CargarDashboard(string fechaInicio, string fechaFinal)
        {
           
            string [] FechaInicioSplit = fechaInicio.Split("-");
            string [] FechaFinalSplit = fechaFinal.Split("-");           

            //Se valida que la fecha de inicio sea menor a la fecha final
            if (Int32.Parse(FechaInicioSplit[0].ToString()) <= Int32.Parse(FechaFinalSplit[0].ToString()) && Int32.Parse(FechaInicioSplit[1].ToString()) <= Int32.Parse(FechaFinalSplit[1].ToString()) && Int32.Parse(FechaInicioSplit[2].ToString()) < Int32.Parse(FechaFinalSplit[2].ToString()) || Int32.Parse(FechaInicioSplit[0].ToString()) < Int32.Parse(FechaFinalSplit[0].ToString()) || Int32.Parse(FechaInicioSplit[0].ToString()) == Int32.Parse(FechaFinalSplit[0].ToString())&& Int32.Parse(FechaInicioSplit[1].ToString()) < Int32.Parse(FechaFinalSplit[1].ToString())) 
            {

                DashboardModel dashboardModel = new DashboardModel();

                BusinessDashboard businessDashboard = new BusinessDashboard(Configuration);
                //Trae los datos segun el rango de fechas cantidad de reuniones tiempo invertido, dinero invertido, asistentes, tipos de reunion esto para todas las reuniones.

                string listaCantidadReuniones = businessDashboard.getCantidadReuniones(fechaInicio, fechaFinal);
                string listaTiempoReuniones = businessDashboard.getCantidadTiempoReuniones(fechaInicio, fechaFinal);
                string listaDineroReuniones = businessDashboard.getCantidadDineroReuniones(fechaInicio, fechaFinal);


                List<CantidadAsistentesModel> ListaCantidadAsistentesModel= new List<CantidadAsistentesModel>();
                List<TipoReunionModel> listaTipoReunionesModel = new List<TipoReunionModel>();
                ListaCantidadAsistentesModel = businessDashboard.getCantidadAsistentesReuniones(fechaInicio, fechaFinal);
                listaTipoReunionesModel = businessDashboard.getListaTiposReuniones(fechaInicio, fechaFinal);



                dashboardModel.TC_Nombre_Meses = ExtraerMeses(FechaInicioSplit[1].ToString(), FechaFinalSplit[1].ToString(), FechaInicioSplit[0].ToString(), FechaFinalSplit[0].ToString());

                //Añade la cantidad de asistentes separados por una , a un string para luego cargarlo en los graficos mas facil
                for (int i = 0; i< ListaCantidadAsistentesModel.Count() ; i++) {
                    dashboardModel.TC_Asistencia_Meses += ListaCantidadAsistentesModel[i].asistencia;

                    if (i == ListaCantidadAsistentesModel.Count()-1)
                    {
                        break;
                    }
                    else {
                        dashboardModel.TC_Asistencia_Meses += ",";
                    }
                }
                dashboardModel.TC_Cantidad_Reunion = listaCantidadReuniones;

                //Añade los tipos de reuniones separados por una , a un string para luego cargarlo en los graficos mas facil
                for (int i = 0; i < listaTipoReunionesModel.Count(); i++)
                {
                    dashboardModel.TC_Tipo_Reunion += listaTipoReunionesModel[i].TN_Cantidad_Tipo_Reunion;
                    dashboardModel.TC_Nombre_Reunion += listaTipoReunionesModel[i].TC_Nombre_Tipo_Reunion;

                    if (i == listaTipoReunionesModel.Count() - 1)
                    {
                        break;
                    }
                    else
                    {
                        dashboardModel.TC_Tipo_Reunion += ",";
                        dashboardModel.TC_Nombre_Reunion += ",";
                    }
                }
             
                dashboardModel.TC_Dinero_Invertido = listaDineroReuniones;
                dashboardModel.TC_Tiempo_Invertido = listaTiempoReuniones;

                ViewBag.ListaDashboard = dashboardModel;

                //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
                ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
                return View("DashboardView");

            }
            else {

                ViewBag.INVALIDO = "La fecha final es menor a la de inicio";
                //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
                ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
                return View("DashboardView");

            }
          
        }


        //Se encarga de agregar los meses en un rango de fechas para luego mostrar en los graficos
        public string ExtraerMeses(string mesInicio, string mesFinal, string annoInicio, string annoFin) {
            string meses = "";
            int mesInicioValidar = Int32.Parse(mesInicio.ToString());
            int mesFinValidar = Int32.Parse(mesFinal.ToString());
            int annoInicioValidar = Int32.Parse(annoInicio.ToString());
            int annoFinValidar = Int32.Parse(annoFin.ToString());

            bool valido = true;
            while (valido) {

                if (mesInicioValidar == 13 && annoInicioValidar < annoFinValidar)
                {
                    annoInicioValidar = annoInicioValidar + 1;
                    mesInicioValidar = 1;
                }


                switch (mesInicioValidar) {
                    case 1:
                        meses += "Enero";
                        break;
                    case 2:
                        meses += "Febrero";
                        break;
                    case 3:
                        meses += "Marzo";
                        break;
                    case 4:
                        meses += "Abril";
                        break;
                    case 5:
                        meses += "Mayo";
                        break;
                    case 6:
                        meses += "Junio";
                        break;
                    case 7:
                        meses += "Julio";
                        break;
                    case 8:
                        meses += "Agosto";
                        break;
                    case 9:
                        meses += "Septiembre";
                        break;
                    case 10:
                        meses += "Octubre";
                        break;
                    case 11:
                        meses += "Noviembre";
                        break;
                    case 12:
                        meses += "Dicembre";
                        break;
                    default:
                        meses = "";
                        break;                        
                }
               

                if (annoInicioValidar == annoFinValidar)
                {
                    if (mesInicioValidar < mesFinValidar)
                    {
                        meses += ",";
                        mesInicioValidar++;
                    }
                    else
                    {
                        valido = false;
                    }

                }
                else if(annoInicioValidar < annoFinValidar)
                {
                    meses += ",";
                    mesInicioValidar++;                  

                }
                

            }

            return meses;
        
        }

    }
}

GestorReunionesProyectoAnalisis/Views/Dashboard/DashboardView.cshtml
@{
    ViewData["Title"] = "DashboardView";

    if (ViewBag.PermisoUsuario == "1")
        {
            Layout = "_Layout";
        }
        else if (ViewBag.PermisoUsuario == "2")
        {
            Layout = "LayoutUsuarioEstandar";
        }
        else if (ViewBag.PermisoUsuario == "3")
        {
            Layout = "LayoutUsuarioCatalogos";
        }

        if (ViewBag.PermisoUsuario == null)
        {
            <script>
                redireccion('/Usuario/MuestraLoginUsuario');
            </script>
        }

}

@model String

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>

<link rel="stylesheet" type="text/css" href="~/css/script.css" />
<link rel="stylesheet" type="text/css" href="~/css/moduloAdministrador.css" />
<link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="~/css/style.css">


<section id="contenido">
    <section id="principal">


        <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">

            <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">

                <div class="signup-form">
                    <form class="form-signin" asp-controller="Dashboard" asp-action="CargarDashboard" method="POST">
                        <h3>Dashboard General</h3>
                        <p class="hint-text">Espacio para buscar informacion sobre las reuniones segun dos rangos de fechas. </p>

                        <div class="form-group">
                            <input type="date" id="fechaInicio" name="fechaInicio" class="form-control" placeholder="Fecha" required="">
                        </div>

                        <div class="form-group">
                            <input type="date" id="fechaFinal" name="fechaFinal" class="form-control" placeholder="Fecha" required="">
                        </div>

                        <div class="form-group"> <button type="submit" class="btn btn-outline-secondary">Ingresar</button> </div>
                        <div class="form-group"><span id="resultadoRespuesta"></span></div>
                        @if (ViewBag.INVALIDO != null)
                        {
                            <div class="alert alert-danger" id="al1" role="alert" style="display: block; text-align:center">
                                <h6> @ViewBag.INVALIDO</h6>
                            </div>
                            
                        }


                    </form>
                </div>
            </div>


        </div>
       

        @if (ViewBag.ListaDashboard != null)
        {

            <div class="album py-5 bg-light">
                <div class="container">

                    <div class="row">
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm text-lg-center">
                                <h3 class="text-muted">Asistencia</h3>
                                <canvas id="myChart" width="400" height="400"></canvas>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm text-lg-center">
                                <h3 class="text-muted">Cantidad de reuniones</h3>
                                <canvas id="graficoBarrasCantidadReuniones" width="400" height="400"></canvas>
                            </div>
                        </div>


                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm text-lg-center">
                                <h3 class="text-muted">Tipo de reuniones</h3>
                                <canvas id="graficoDonaTipo" width="200" height="200"></canvas>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm text-lg-center">
                                <h3 class="text-muted">Dinero invertido</h3>
                                <canvas id="gfclineaDinero" width="200" height="200"></canvas>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm text-lg-center">
                                <h3 class="text-muted">Tiempo invertido</h3>
                                <canvas id="gfclineaTiempo" width="200" height="200"></canvas>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        }

    </section>
</section>


@if (ViewBag.ListaDashboard != null)
{

    DashboardModel temp = ViewBag.ListaDashboard;

    <input id="TC_Nombre_Meses" name="iptIDReunion" class="form-control" value="@temp.TC_Nombre_Meses" hidden />
    <input id="TC_Asistencia_Meses" name="iptNombreReunion" class="form-control" value="@temp.TC_Asistencia_Meses" hidden />
    <input id="TC_Cantidad_Reunion" name="iptNombreReunion" class="form-control" value="@temp.TC_Cantidad_Reunion" hidden />
    <input id="TC_Tipo_Reunion" name="iptNombreReunion" class="form-control" value="@temp.TC_Tipo_Reunion " hidden />
    <input id="TC_Nombre_Reunion" name="iptNombreReunion" class="form-control" value="@temp.TC_Nombre_Reunion" hidden />
    <input id="TC_Dinero_Invertido" name="iptFechaReunion" class="form-control" value="@temp.TC_Dinero_Invertido" hidden />
    <input id="TC_Tiempo_Invertido" name="iptFechaReunion" class="form-control" value="@temp.TC_Tiempo_Invertido" hidden />


    <script>

        //alert(document.getElementById("TC_Nombre_Meses").value);
        var nombreMeses = document.getElementById("TC_Nombre_Meses").value;
        nombreMesesSplit = nombreMeses.split(',');

        var asistenciaReunion= document.getElementById("TC_Asistencia_Meses").value;
        asistenciaReunionSplit = asistenciaReunion.split(',');

        var cantidadReunion = document.getElementById("TC_Cantidad_Reunion").value;
        cantidadReunionSplit = cantidadReunion.split(',');

        var TipoReunion = document.getElementById("TC_Tipo_Reunion").value;
        TipoReunionSplit = TipoReunion.split(',');

        var NombreReunion = document.getElementById("TC_Nombre_Reunion").value;
        NombreReunionSplit = NombreReunion.split(',');

        var DineroReunion = document.getElementById("TC_Dinero_Invertido").value;
        DineroReunionSplit = DineroReunion.split(',');

        var TiempoReunion = document.getElementById("TC_Tiempo_Invertido").value;
        TiempoReunionSplit = TiempoReunion.split(',');

        // Enero,febrero

        var ctx = document.getElementById('myChart');
        var myChart = new Chart(ctx, {
            type: 'line',

            data: {
                
                labels: nombreMesesSplit,
                datasets: [{
                    label: 'Mensual',
                    data: asistenciaReunionSplit,
                    backgroundColor: 'rgba(241, 196, 15 , 0.4)',
                    borderColor: 'rgba(46, 64, 83 , 0.6)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });



        var graficoBarrasCantidadReuniones = document.getElementById('graficoBarrasCantidadReuniones');
        var gfcBarTipo = new Chart(graficoBarrasCantidadReuniones, {
            type: 'bar',

            data: {
                labels: nombreMesesSplit,
                datasets: [{
                    label: 'Mensual',
                    data: cantidadReunionSplit,
                    backgroundColor: 'rgba(241, 196, 15  , 0.5)',
                    borderColor: 'rgba(46, 64, 83 , 0.6)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });



        var graficoDonaTipo = document.getElementById('graficoDonaTipo');


        var gfcPieTipo = new Chart(graficoDonaTipo, {
            type: 'doughnut',

            data: {
                labels: NombreReunionSplit,
                datasets: [{


                    label: 'Mensual',
                    data: TipoReunionSplit,
                    borderColor: 'rgba(46, 64, 83 , 0.6)',
                    backgroundColor: colorRGB(20),
                    borderWidth: 3
                }]
            }

        });






        var gfclineaDinero = document.getElementById('gfclineaDinero');
        var myChart = new Chart(gfclineaDinero, {
            type: 'line',

            data: {
                labels: nombreMesesSplit,
                datasets: [{
                    label: 'Colones',
                    data: DineroReunionSplit,
                    backgroundColor: 'rgba(241, 196, 15 , 0.4)',
                    borderColor: 'rgba(46, 64, 83 , 0.6)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });




        var gfclineaTiempo = document.getElementById('gfclineaTiempo');
        var myChart = new Chart(gfclineaTiempo, {
            type: 'line',

            data: {
                labels: nombreMesesSplit,
                datasets: [{
                    label: 'Horas',
                    data: TiempoReunionSplit,
                    backgroundColor: 'rgba(241, 196, 15 , 0.4)',
                    borderColor: 'rgba(46, 64, 83 , 0.6)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });



        function generarNumero(numero) {

            return (Math.random() * numero).toFixed(0);
        }

        function colorRGB(numero) {
            var coolor = ['rgba(212, 172, 13, 0.9)'];
            for (var i = 0; i < numero; i++) {
                coolor.push("rgba(" + generarNumero(255) + "," + generarNumero(255) + "," + generarNumero(255) + ", 0.5)");
            }

            return coolor;
        }





    </script>

}