GestorReunionesProyectoAnalisis/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using GestorReunionesProyectoAnalisis.Models;
using GestorReunionesProyectoAplicada.Business;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;


namespace GestorReunionesProyectoAplicada.Controllers
{
    public class UsuarioController : Controller
    {

        public IConfiguration Configuration { get; }

        public UsuarioController(IConfiguration configuration)
        {
            Configuration = configuration;
        } // constructor


        //Abre la vista para crear un usuario, envia 3 listas con las oficinas, roles y puestos a la vista
        public IActionResult MuestraCrearUsuario()
        {

            BusinessCatalogo businessCatalogo = new BusinessCatalogo(Configuration);
           
            List<PuestoModel> listaPuesto = new List<PuestoModel>();
            List<OficinaModel> listaOficina = new List<OficinaModel>();
            List<RolModel> listaRol = new List<RolModel>();
            
            listaPuesto = businessCatalogo.getListarCatalogoPuesto();
            listaOficina = businessCatalogo.getListarCatalogoOficina();
            listaRol = businessCatalogo.getListarCatalogoRol();

            ViewBag.ListaPuestos = listaPuesto;
            ViewBag.ListaRoles = listaRol;
            ViewBag.ListaOficinas = listaOficina;


            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
            return View("CrearUsuario");
        }


        //Se encarga de mostrar el login del usuario
        public IActionResult MuestraLoginUsuario()
        {

            //Se limpian las variables en session
            HttpContext.Session.SetString("UsuarioLogin", "");
            HttpContext.Session.SetString("UsuarioPermiso","");
            return View("LoginView");
        }


        //Valida si el usuario existe para que ingrese al sistema
        [HttpPost]
        public IActionResult LoginUsuario(LoginModel loginModel)
        {

            //Se crea un objeto usuario y se le asigna un valor desde la base de datos
            UsuarioModel usuarioModel = new UsuarioModel();
           
            BusinessUsuario bussinesUsuario = new BusinessUsuario(Configuration);
            usuarioModel = bussinesUsuario.LoginUsuario(loginModel);

            //Si es diferente de null es que existe por lo tanto pasa a la siguiente vista, en caso contrario regresa al login con un mensaje de error
            if (usuarioModel != null) {

                HttpContext.Session.SetString("UsuarioLogin", usuarioModel.Usuario);
                HttpContext.Session.SetString("UsuarioPermiso", usuarioModel.Permisos.ToString());
                //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
                ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");

                BusinessAgenda businessAgenda = new BusinessAgenda(Configuration);
                List<ReunionModel> listaReuniones = new List<ReunionModel>();

                //Se extraen las reuniones de las base para colocarlas en el calendario
                listaReuniones = businessAgenda.getReuniones(HttpContext.Session.GetString("UsuarioLogin"));

                ViewBag.ListaReuniones = listaReuniones;

             
                return View("/Views/Agenda/Calendario.cshtml");
                

            }
            else {
                String ERROR = " Error en las credenciales";
                ViewBag.ERROR = ERROR;
                return View("LoginView");                
            }

        } // Login Usuario



        //Se utiliza insertar usuario en bases de datos 
        [HttpPost]
        public IActionResult CrearUsuario(UsuarioModel usuarioModel)
        {

            BusinessUsuario businessUsuario = new BusinessUsuario(Configuration);

            bool valido = false;

            string contrasena = usuarioModel.Contrasena;
            int valoresNumericos = 0;
            int valoresString = 0;
            int valorMaximo = 0;

            //Se realiza un conteo de cuantos numero y letras trae la contraseña
            for (int i = 0; i < contrasena.Length; i++)
            {

                if (Char.IsNumber(contrasena[i]) == true)
                {
                    valoresNumericos++;
                }
                else
                {
                    valoresString++;
                }
            }

            valorMaximo = valoresNumericos + valoresString;

            //Se valida que cumpla con un minimo de 3 numeros y 4 letras y que no sea mayor a 16 caracteres
            if (valoresNumericos >= 3 && valoresString >= 4 && valorMaximo < 16)
            {
                
                //Se valida que los campos que se insertaron no vengan en blanco
                if (usuarioModel.Nombre != null && usuarioModel.PrimerApellido != null && usuarioModel.SegundoApellido != null && usuarioModel.Cedula != null && usuarioModel.Usuario != null && usuarioModel.Correo != null && usuarioModel.Contrasena != null)
                {
                    //Si el usuario se inserta con exito valido=True en caso contrario es False
                    valido = businessUsuario.CrearUsuario(usuarioModel);
                }
                else
                {
                    valido = false;
                }
            }
            else
            {
                ViewBag.ErrorContrasena = "La contraseña requiere un minimo de 3 numeros y 4 letras";
              
            }

            BusinessCatalogo businessCatalogo = new BusinessCatalogo(Configuration);

            List<PuestoModel> listaPuesto = new List<PuestoModel>();
            List<OficinaModel> listaOficina = new List<OficinaModel>();
            List<RolModel> listaRol = new List<RolModel>();

            //Se trae la informacion que requieren la interfaz para realizar la insercion de un usuario, en este caso lista de puestos, roles, oficinas
            listaPuesto = businessCatalogo.getListarCatalogoPuesto();
            listaOficina = businessCatalogo.getListarCatalogoOficina();
            listaRol = businessCatalogo.getListarCatalogoRol();

            ViewBag.ListaPuestos = listaPuesto;
            ViewBag.ListaRoles = listaRol;
            ViewBag.ListaOficinas = listaOficina;
            
            // valido = TRUE exito, de lo contrario no se inserto el usuario
            if (valido)
            {
                ViewBag.EXITO = "Exito al guardar";
            }
            else
            {                

                ViewBag.ERROR = "Error al guardar";
            }

            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
            return View("CrearUsuario");
           
        } // Crear Usuario



        //Se realiza la eliminación de un usuario
        [HttpPost]
        public IActionResult EliminarUsuario(UsuarioModel usuarioModel)
        {

            BusinessUsuario businessUsuario = new BusinessUsuario(Configuration);
            List<UsuarioModel> listaUsuarios = new List<UsuarioModel>();

            //Se retorna la lista de usuarios que esta en la base de datos, si consiguio ser borrado se vera reflejado en la interfaz
            listaUsuarios = businessUsuario.EliminarUsuario(usuarioModel);

            ViewBag.ListaUsuarios = listaUsuarios;

            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
            return View("ModificarContactoView");

        } // Eliminar Usuario
        

        //listar usuarios existentes en interfaz para eliminar y modificar
        public IActionResult viewListarUsuario()
        {
            BusinessUsuario businessUsuario = new BusinessUsuario(Configuration);
            List<UsuarioModel> listaUsuarios = new List<UsuarioModel>();
            //Se listan los usuarios de la base de datos
            listaUsuarios = businessUsuario.getListarUsuario();

            ViewBag.ListaUsuarios = listaUsuarios;

            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
            return View("ModificarContactoView");
        }


        //Carga las listas de Oficina, Roles, Puesto y Los datos del usuario los manda a interfaz para poder realiza la modificación
        [HttpPost]
        public IActionResult VistaModificarUsuario(UsuarioModel usuarioModel)
        {

            BusinessUsuario businessUsuario = new BusinessUsuario(Configuration);
            UsuarioModel usuarioModificar = new UsuarioModel();
            
            //Se trae de la base el usuario con el ID que solicito el usuario
            usuarioModificar = businessUsuario.getUsuarioModificar(usuarioModel);

            //Se valida si ese usuario existia sin no existe se retorna la vista anterior con todos los usuarios
            if (usuarioModificar != null)
            {
                BusinessCatalogo businessCatalogo = new BusinessCatalogo(Configuration);

                List<PuestoModel> listaPuesto = new List<PuestoModel>();
                List<OficinaModel> listaOficina = new List<OficinaModel>();
                List<RolModel> listaRol = new List<RolModel>();

                //Se listan Roles, Oficinas, Puestos para poder cargarlos en interfaz y que se realice la modificaion del usuario

GestorReunionesProyectoAnalisis/Views/Usuario/CrearUsuario.cshtml
@{
    ViewData["Title"] = "CrearUsuario";

    if (ViewBag.PermisoUsuario == "1")
    {
        Layout = "_Layout";
    }
    else if (ViewBag.PermisoUsuario == "2")
    {
        Layout = "LayoutUsuarioEstandar";
    }
    else if (ViewBag.PermisoUsuario == "3")
    {
        Layout = "LayoutUsuarioCatalogos";
    }

    if (ViewBag.PermisoUsuario == null)
    {
        <script>
            redireccion('/Usuario/MuestraLoginUsuario');
        </script>
    }


}

<link rel="stylesheet" type="text/css" href="~/css/script.css" />
<link rel="stylesheet" type="text/css" href="~/css/moduloAdministrador.css" />
<link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="~/css/style.css">

<section id="contenidoR" style="margin-top:60px">
    <section id="principalR">

        <br><br>
        <div content="width=device-widt" class="row">
            <div class="signup-form col-sm-8">

                <form class="form-signin" asp-controller="Usuario" asp-action="CrearUsuario" method="POST">
                    <center>
                        <h3>Crear Usuario</h3>

                        <p class="hint-text">Los usuarios será creados unicamente por administradores. </p>
                        <div content="width=device-widt" class="row">

                            <div class="col-sm-6">
                                <h9> </h9> <!--Corregir desfase-->
                                <div class="form-group"><input id="nombre" name="nombre" type="text" placeholder="Nombre" class="form-control" required></div>
                                <div class="form-group"><input id="primerApellido" name="primerApellido" type="text" placeholder="Primer apellido" class="form-control" required></div>
                                <div class="form-group"><input id="segundoApellido" name="segundoApellido" type="text" placeholder="Segundo  apellido" class="form-control" required></div>
                                <div class="form-group"><input id="cedula" name="cedula" type="number" placeholder="Cedula" class="form-control" required></div>
                                <div class="form-group"><input id="usuario" name="usuario" type="text" placeholder="Usuario" class="form-control" required></div>
                                <h9> </h9> <!--Corregir desfase-->

                            </div>

                            <div class="col-sm-6">

                                <h9> </h9> <!--Corregir desfase-->
                                <div class="form-group"><input id="correo" name="correo" type="text" placeholder="Correo" class="form-control" required></div>
                                <div class="form-group"><input id="contrasena" name="contrasena" type="password" placeholder="Contraseña" class="form-control" required></div>

                                <div class="form-group">
                                    <select id="oficina" name="oficina" class="form-control">

                                        <option value="0">Oficina</option>
                                        @if (ViewBag.ListaOficinas != null)
                                        {

                                            @foreach (OficinaModel temp in ViewBag.ListaOficinas)
                                            {
                                                <option value="@temp.TN_Id_Oficina">@temp.TC_Nombre</option>

                                            }
                                        }

                                    </select>
                                </div>

                                <div class="form-group">
                                    <select id="puesto" name="puesto" class="form-control">
                                        <option value="0">Puestos</option>
                                        @if (ViewBag.ListaPuestos != null)
                                        {

                                            @foreach (PuestoModel temp in ViewBag.ListaPuestos)
                                            {
                                                <option value="@temp.TN_Id_Puesto">@temp.TC_Nombre_Puesto</option>

                                            }
                                        }
                                    </select>
                                </div>

                                <div class="form-group">
                                    <select id="rol" name="rol" class="form-control">
                                        <option value="0">Rol</option>
                                        @if (ViewBag.ListaRoles != null)
                                        {

                                            @foreach (RolModel temp in ViewBag.ListaRoles)
                                            {
                                                <option value="@temp.TN_Id_Rol">@temp.TC_Nombre_Rol</option>

                                            }
                                        }
                                    </select>
                                </div>
                                <h9> </h9> <!--Corregir desfase-->

                            </div>
                        </div>

                        <div class="form-group"><button class="btn btn-outline-secondary btn-block" type="submit">Finalizar</button><br></div>


                        @if (ViewBag.ERROR != null && ViewBag.ErrorContrasena == null)
                        {
                            <div class="alert alert-danger" id="al1" role="alert" style="display: block; text-align:center">
                                <h6> @ViewBag.ERROR</h6>
                            </div>
                            <br>

                        }


                        @if (ViewBag.EXITO != null )
                        {
                            <div class="alert alert-info" id="al1" role="contentinfo" style="display: block; text-align:center">
                                <h6> @ViewBag.EXITO</h6>
                            </div>
                            <br>

                        }


                        @if (ViewBag.ErrorContrasena != null)
                        {
                            <div class="alert alert-danger" id="al1" role="contentinfo" style="display: block; text-align:center">
                                <h6> @ViewBag.ErrorContrasena</h6>
                            </div>
                            <br>

                        }

                        

                    </center>

                </form>

            </div>
        </div>

    </section>
</section>

GestorReunionesProyectoAnalisis/Views/Usuario/LoginView.cshtml
@{
    ViewData["Title"] = "LoginUsuarios";
    Layout = "_LayoutLoginUsuario";

    // if (ViewBag.ReiniciarSession == null)
    //{
        <script>
          //  redireccion('/Usuario/MuestraLoginUsuario');
        </script>
        //}


        //@ViewBag.ReiniciarSession = null;
    }
<span id="LoginDatos"></span>

@model String
<link rel="stylesheet" type="text/css" href="~/css/script.css" />
<link rel="stylesheet" type="text/css" href="~/css/moduloAdministrador.css" />
<link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="~/css/style.css">

<section id="contenidoR" style="margin-top:60px">
    <section id="principalR">

        <div class=" d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
            <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
                <div class="signup-form container-fluid" style="width: 63%;">
                    <form class="form-signin" id="iniciaSesion" asp-controller="Usuario" asp-action="LoginUsuario" method="POST">
                        <h2>Iniciar Sesión</h2>

                        <div class="form-group">
                            <input type="text" id="nombre" name="nombre" class="form-control" placeholder="Nombre de usuario" required="" autofocus="">
                        </div>
                        <div class="form-group">
                            <input type="password" id="contrasena" name="contrasena" class="form-control" placeholder="Contraseña" required="">
                        </div>
                        <div class="form-group "><button class="btn btn-outline-secondary btn-block" type="submit">Iniciar Sesion</button></div>

                        @if (ViewBag.ERROR != null)
                        {
                            <div class="alert alert-danger" id="al1" role="alert" style="display: block; text-align:center">
                                @Model
                                <h6> @ViewBag.ERROR</h6>
                            </div>
                            <br>
                        }
                    </form>
                </div>
            </div>
        </div>

    </section>
</section>

GestorReunionesProyectoAnalisis/Views/Usuario/ModificarContactoView.cshtml
@{
    ViewData["Title"] = "ModificarContacto";

    if (ViewBag.PermisoUsuario == "1")
    {
        Layout = "_Layout";
    }
    else if (ViewBag.PermisoUsuario == "2")
    {
        Layout = "LayoutUsuarioEstandar";
    }
    else if (ViewBag.PermisoUsuario == "3")
    {
        Layout = "LayoutUsuarioCatalogos";
    }

    if (ViewBag.PermisoUsuario == null)
    {
        <script>
            redireccion('/Usuario/MuestraLoginUsuario');
        </script>
    }

}


<section id="contenidoC" style="margin-top:80px">
    <section id="principalC">
        <CENTER>
            <div content="width=device-widt" class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-8">
                    <h1>Modificar Contacto</h1>

                    <table id="consultaC" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                        <thead class="thead-dark">
                            <tr>
                                <th>Nombre </th>
                                <th>Apellidos </th>
                                <th>Puesto </th>
                                <th>Oficina </th>
                                <th>Modificar</th>
                                <th>Eliminar</th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (UsuarioModel temp in ViewBag.ListaUsuarios)
                            {
                                <tr>
                                    <td>@temp.Nombre</td>
                                    <td>@temp.PrimerApellido @temp.SegundoApellido</td>
                                    <td>@temp.Puesto</td>
                                    <td>@temp.Oficina</td>

                                    <form asp-action="VistaModificarUsuario" asp-controller="Usuario" method="post">

                                        <td>
                                            <input id="idUsuario" name="idUsuario" class="form-control" value="@temp.IdUsuario" hidden />
                                            <button type="submit" class="btn btn-secondary">Modificar</button>
                                        </td>

                                    </form>



                                    <form asp-action="EliminarUsuario" asp-controller="Usuario" method="post">
                                        <td>
                                            <input id="idUsuario" name="idUsuario" class="form-control" value="@temp.IdUsuario" hidden />
                                            <button type="submit" class="btn btn-danger">Eliminar</button>
                                        </td>
                                    </form>



                                </tr>
                            }


                        </tbody>
                    </table>
                    @if (ViewBag.ERROR != null)
                    {
                        <div class="alert alert-danger" id="al1" role="alert" style="display: block; text-align:center">
                            <h6> @ViewBag.ERROR</h6>
                        </div>
                        <br>

                    }



                </div>
                <div class="col-sm-2"></div>
            </div>

        </CENTER>
    </section>
</section>