GestorReunionesProyectoAnalisis/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using GestorReunionesProyectoAnalisis.Business;
using GestorReunionesProyectoAnalisis.Models;
using GestorReunionesProyectoAplicada.Business;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace GestorReunionesProyectoAplicada.Controllers
{
    public class AgendaController : Controller
    {
        public IConfiguration Configuration { get; }

        public AgendaController(IConfiguration configuration)
        {
            Configuration = configuration;
        } // constructor

        public IActionResult Index()
        {
            return View();
        }

        //Carga la vista de la agenda personal
        public IActionResult ViewAgendaPersonal()
        {

            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");

            BusinessAgenda businessAgenda = new BusinessAgenda(Configuration);
            List<ReunionModel> listaReuniones = new List<ReunionModel>();           

            //Retorna todas las reuniones que tenga el usuario que este en linea
            listaReuniones = businessAgenda.getReuniones(HttpContext.Session.GetString("UsuarioLogin"));
            ViewBag.ListaReuniones = listaReuniones;
           
            return View("Calendario");
            
            
        }


        //Lista los asistentes que posee una reunion
        public IActionResult CargarAsistentesReunion(string IdReunionAsistentes)
        {

            BusinessAgenda businessAgenda = new BusinessAgenda(Configuration);
            List<UsuarioModel> ListaAsistentesReunion = new List<UsuarioModel>();
            //lista los asistentes
            ListaAsistentesReunion = businessAgenda.getAsistentesReunion(IdReunionAsistentes);

            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
            
            List<ReunionModel> listaReuniones = new List<ReunionModel>();

            //Lista nuevamente las reuniones para que se vean en el calendario
            listaReuniones = businessAgenda.getReuniones(HttpContext.Session.GetString("UsuarioLogin"));
           
            //valida si la lista es != null crea el ViewBag que lleva la lista de usuarios de lo contrario no lo crea y no mostraria ninguna lista en interfaz
            if (ListaAsistentesReunion != null)
            {
                ViewBag.ListaReuniones = listaReuniones;
                ViewBag.ListaUsuarios = ListaAsistentesReunion;
                return View("Calendario");
            }
            else
            {
                ViewBag.ListaReuniones = listaReuniones;
                return View("Calendario");
            }                           

        }





        //Lista de las tareas que posee una reunion
        public IActionResult CargarTareasReunion(string IdReunionTareas)
        {
           
            BusinessAgenda businessAgenda = new BusinessAgenda(Configuration);
            List<TareaModel> ListaTareasReunion = new List<TareaModel>();
            //lista de tareas
            ListaTareasReunion = businessAgenda.getTareasReunion(IdReunionTareas);

            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");

            List<ReunionModel> listaReuniones = new List<ReunionModel>();

            //Lista las reuniones que tenga el usuario que esta en linea para ponerlas en el calendario
            listaReuniones = businessAgenda.getReuniones(HttpContext.Session.GetString("UsuarioLogin"));
            ViewBag.ListaReuniones = listaReuniones;

            //valida la existencia de la lista de tareas para retornarlas a interfaz
            if (ListaTareasReunion != null)
            {
                ViewBag.ListaTareas = ListaTareasReunion;
                return View("Calendario");
            }
            else
            {
                return View("Calendario");
            }

        }

        //Lista de los archivos que posee una reunion
        public IActionResult CargarArchivosReunion(string IdReunionArchivos)
        {    

            List<ArchivoModel> listaArchivos = new List<ArchivoModel>();
            BusinessArchivos businessArchivos = new BusinessArchivos(Configuration);
            //lista archivos
            listaArchivos = businessArchivos.listarArchivos(IdReunionArchivos);

            BusinessAgenda businessAgenda = new BusinessAgenda(Configuration);            
            List<ReunionModel> listaReuniones = new List<ReunionModel>();

            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");

            //Lista las reuniones que tenga el usuario que esta en linea para ponerlas en el calendario
            listaReuniones = businessAgenda.getReuniones(HttpContext.Session.GetString("UsuarioLogin"));
            ViewBag.ListaReuniones = listaReuniones;

            //valida la existencia de la lista de archivos para retornarlos a interfaz
            if (listaArchivos != null)
            {
                ViewBag.ListaArchivos = listaArchivos;
                return View("Calendario");
            }
            else
            {
                return View("Calendario");
            }

        }

    }
}

GestorReunionesProyectoAnalisis/Controllers/TareaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GestorReunionesProyectoAnalisis.Models;
using GestorReunionesProyectoAplicada.Business;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace GestorReunionesProyectoAplicada.Controllers
{
    public class TareaController : Controller
    {

        public IConfiguration Configuration { get; }

        public TareaController(IConfiguration configuration)
        {
            Configuration = configuration;
        } // constructor

        public IActionResult Index()
        {
            return View();
        }


        // Mostrar la vista de crear Tarea
        public IActionResult viewCrearTarea()
        {
            
            List<UsuarioModel> listaUsuarios = new List<UsuarioModel>();
            BusinessUsuario businessUsuario = new BusinessUsuario(Configuration);
            //Se trae toda la lista de usuarios para luego poder crear la tarea en la interfaz
            listaUsuarios = businessUsuario.getListarUsuario();

            ViewBag.ListaUsuarios = listaUsuarios;

            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
            return View("CrearTareaView");
        }


        //Se encarga de mostrar todas la tareas que se han creado para poder eliminarlas o modificarlas
        public IActionResult viewBuscarTarea()
        {
            List<TareaModel> listaTareas= new List<TareaModel>();

            BusinessTarea businessTarea = new BusinessTarea(Configuration);
            //Lista las tareas de la base de datos
            listaTareas = businessTarea.getListarTarea();

            ViewBag.ListaTareas = listaTareas;
            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
            return View("BuscarTareasView");
        }


        //Trae la tarea de la base de datos que el usuarios seleciono
        public IActionResult viewModificarTarea(string idTarea)
        {

            List<UsuarioModel> listaUsuarios = new List<UsuarioModel>();
            BusinessUsuario businessUsuario = new BusinessUsuario(Configuration);

            //Lista los usuarios, por si se desea modificar los usuarios de esa tarea
            listaUsuarios = businessUsuario.getListarUsuario();

            ViewBag.ListaUsuarios = listaUsuarios;


            BusinessTarea businessTarea = new BusinessTarea(Configuration);
            TareaModel tareaModificar = new TareaModel();

            //Lista la tarea que el usuario solicito modificar atravez del id de la misma
            tareaModificar = businessTarea.getTareaModificar(idTarea);

            ViewBag.TareaModificar = tareaModificar;

            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
            return View("ModificarTareaView");
            //return new JsonResult(idTarea);
            //return new JsonResult(ViewBag.TareaModificar.TC_Nombre_Tarea);
        }


        //Eliminar una tarea segun su id
        public IActionResult EliminarTarea(string idTarea)
        {

            List<TareaModel> listaTareas = new List<TareaModel>();
            BusinessTarea businessTarea = new BusinessTarea(Configuration);

            //Elimina la tarea y retorna la lista de todas la tareas, de esta manera en interfaz se podra ver si efectivamente se borro
            listaTareas = businessTarea.EliminarTarea(idTarea);

            ViewBag.ListaTareas = listaTareas;

            //El ViewBag.PermisoUsuario se utiliza controlar el inicio de session de un usuario y su respectivos permisos
            ViewBag.PermisoUsuario = HttpContext.Session.GetString("UsuarioPermiso");
            return View("BuscarTareasView");
           
        }
        

        //Se encarga de agregar la tarea a la base de datos
        [HttpPost]
        public IActionResult CrearTarea(TareaModel tareaModel)
        {
                  
            BusinessTarea businessTarea = new BusinessTarea(Configuration);
            //Se encarga de crear la tarea en caso de exito retorna un true y le notifica al usuario del exito de la operacion
            bool valido = businessTarea.CrearTarea(tareaModel);

            if (valido)
            {
                //return a java script
                return new JsonResult("Si Creo");
            }
            else
            {
                //return a java script
                return new JsonResult("No guardo");                
            }
            
        }


        //Modificar una tarea 
        [HttpPost]
        public IActionResult ModificarTarea(TareaModel tareaModel)
        {
            
            BusinessTarea businessTarea = new BusinessTarea(Configuration);

            //Si la tarea fue modificada retorna true y le notifica al usuario del exito de la operacion
            bool valido = businessTarea.ModificarTarea(tareaModel);

            if (valido)
            {
                //return a java script
                return new JsonResult("Si modifico");
            }
            else
            {
                //return a java script
                return new JsonResult("No guardo");                
            }
           
        }
    }
}

GestorReunionesProyectoAnalisis/Views/Shared/LayoutUsuarioCatalogos.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Gestor reuniones OIJ</title>
    <meta charset="utf-8" />
    <meta name="description" content="Gestor de reuniones para OIJ" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="~/img/escudo.ico" />


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link href="../assets/dist/css/bootstrap.css" rel="stylesheet">
        <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">*@
    @*<link href="navbar.css" rel="stylesheet">*@
    <link href="navbar.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link rel="stylesheet" type="text/css" href="~/css/script.css" />*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- JS-->
    <script type="text/javascript" src="~/js/jquery-3.2.1.js"></script>
    <script type="text/javascript" src="~/js/script7.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>
    <script type="text/javascript" src="~/js/ScriptModals.js"></script>
    <script type="text/javascript" src="~/js/ScriptTarea.js"></script>
    <script type="text/javascript" src="~/js/ScriptReunion.js"></script>
    <script type="text/javascript" src="~/js/calendar.js"></script>

    <!--DATATABLES-->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />

</head>

<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-dark">
            <a class="navbar-brand" ><img src="~/img/escudoNav32.png" title="title" alt="additional title" /> Gestor de Reuniones OIJ</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample03">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Usuario</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown03">
                            <a class="dropdown-item" asp-controller="Usuario" asp-action="muestraCrearUsuario">Nuevo</a>
                            <a class="dropdown-item" asp-controller="Usuario" asp-action="viewListarUsuario">Modificar</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Catálogos</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown03">
                            <a class="dropdown-item" asp-controller="Catalogo" asp-action="viewTipoReunionCatalogo">Tipo reunión</a>
                            <a class="dropdown-item" asp-controller="Catalogo" asp-action="viewOfinaCatalogo">Oficina</a>
                            <a class="dropdown-item" asp-controller="Catalogo" asp-action="viewRolSistemaCatalogo">Rol de sistema</a>
                            <a class="dropdown-item" asp-controller="Catalogo" asp-action="viewPuestoUsuarioCatalogo">Puesto Usuario</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link " asp-controller="Agenda" asp-action="ViewAgendaPersonal">Agenda personal</a>
                    </li>
                </ul>

                @*<form class="form-inline my-2 my-md-0">
            <button type="button" class="btn btn-outline-warning">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bell-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z" />
                </svg>
            </button>
        </form>*@
                <form class="form-inline my-2 my-md-0" asp-controller="Usuario" asp-action="MuestraLoginUsuario">
                    <button type="submit" class="btn btn-outline-warning"> Salir</button>
                </form>

            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        <div class="container-fluid" style="width:90%">
            @RenderBody()
        </div>
    </main>


    <footer class="border-top footer text-muted">
        @*<div class="container">
                &copy; 2020 - GestorReunionesProyectoAplicada - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>*@
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <!--<script src="https://code.jquery.com/jquery-3.5.1.js"></script>-->
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>


</body>
</html>

GestorReunionesProyectoAnalisis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Gestor reuniones OIJ</title>
    <meta charset="utf-8" />
    <meta name="description" content="Gestor de reuniones para OIJ" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="~/img/escudo.ico" />


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link href="../assets/dist/css/bootstrap.css" rel="stylesheet">
        <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">*@
    @*<link href="navbar.css" rel="stylesheet">*@
    <link href="navbar.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link rel="stylesheet" type="text/css" href="~/css/script.css" />*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>

    <!-- JS-->
    <script type="text/javascript" src="~/js/jquery-3.2.1.js"></script>
    <script type="text/javascript" src="~/js/script7.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>
    <script type="text/javascript" src="~/js/ScriptModals.js"></script>
    <script type="text/javascript" src="~/js/ScriptTarea.js"></script>
    <script type="text/javascript" src="~/js/ScriptReunion.js"></script>
    <script type="text/javascript" src="~/js/calendar.js"></script>

    <!--DATATABLES-->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />

</head>

<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-dark">
            <a class="navbar-brand"><img src="~/img/escudoNav32.png" title="title" alt="additional title" /> Gestor de Reuniones OIJ</a>
         
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarsExample03">
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#iiii" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Reuniones</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown03">
                                <a class="dropdown-item" asp-controller="Reunion" asp-action="viewCrearReunion">Nuevo</a>
                                <a class="dropdown-item" asp-controller="Reunion" asp-action="viewBuscaReunion">Modificar</a>
                                <a class="dropdown-item" asp-controller="Reunion" asp-action="viewMostrarReunion">Historial</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tarea</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown03">
                                <a class="dropdown-item" asp-controller="Tarea" asp-action="viewCrearTarea">Nuevo</a>
                                <a class="dropdown-item" asp-controller="Tarea" asp-action="viewBuscarTarea">Modificar</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Usuario</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown03">
                                <a class="dropdown-item" asp-controller="Usuario" asp-action="muestraCrearUsuario">Nuevo</a>
                                <a class="dropdown-item" asp-controller="Usuario" asp-action="viewListarUsuario">Modificar</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Catálogos</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown03">
                                <a class="dropdown-item" asp-controller="Catalogo" asp-action="viewTipoReunionCatalogo">Tipo reunión</a>
                                <a class="dropdown-item" asp-controller="Catalogo" asp-action="viewOfinaCatalogo">Oficina</a>
                                <a class="dropdown-item" asp-controller="Catalogo" asp-action="viewRolSistemaCatalogo">Rol de sistema</a>
                                <a class="dropdown-item" asp-controller="Catalogo" asp-action="viewPuestoUsuarioCatalogo">Puesto Usuario</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link " asp-controller="Agenda" asp-action="ViewAgendaPersonal">Agenda personal</a>

                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link " asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>
                    </ul>

                    @*<form class="form-inline my-2 my-md-0">
            <button type="button" class="btn btn-outline-warning">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bell-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z" />
                </svg>
            </button>
        </form>*@

                    <form class="form-inline my-2 my-md-0" asp-controller="Usuario" asp-action="MuestraLoginUsuario">
                        <button type="submit" class="btn btn-outline-warning"> Salir</button>
                    </form>

                </div>
            </nav>
        </header>

        <main role="main" class="pb-3">
            <div class="container-fluid" style="width:90%">
                @RenderBody()
            </div>
        </main>


        <footer class="border-top footer text-muted">
            @*<div class="container">
                    &copy; 2020 - GestorReunionesProyectoAplicada - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>*@
            </footer>

            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @RenderSection("Scripts", required: false)

            <!--<script src="https://code.jquery.com/jquery-3.5.1.js"></script>-->
            <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>


</body>
</html>

GestorReunionesProyectoAnalisis/Views/Shared/_LayoutLoginUsuario.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Gestor reuniones OIJ</title>
    <meta charset="utf-8" />
    <meta name="description" content="Gestor de reuniones para OIJ" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="~/img/escudo.ico" />


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="../assets/dist/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="navbar.css" rel="stylesheet">
    <link href="navbar.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" type="text/css" href="~/css/script.css" />*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- JS-->
    <script type="text/javascript" src="~/js/jquery-3.2.1.js"></script>
    <script type="text/javascript" src="~/js/script7.js"></script>
    <script type="text/javascript" src="~/js/ScriptTarea.js"></script>
    <script type="text/javascript" src="~/js/ScriptModals.js"></script>
    <script type="text/javascript" src="~/js/calendar.js"></script>

    <!--DATATABLES-->

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />



</head>

<body class="bg-light">
    <header>
    
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @*<div class="container">
                &copy; 2020 - GestorReunionesProyectoAplicada - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>*@
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <!--<script src="https://code.jquery.com/jquery-3.5.1.js"></script>-->
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>


</body>
</html>